### PR TITLE
Don't include deprecated versions when using yarn package manager

### LINKED ISSUE #906: `--target minor` includes deprecated versions when using yarn
- [x] I have searched for [similar issues](https://github.com/raineorshine/npm-check-updates/issues)
- [x] I am using the latest version of `npm-check-updates`
- [x] I am using `node >= 10.17`

---------------------------

## Steps to Reproduce

From a new directory:
1. `npm init -y`
2. `npm install @progress/kendo-drawing`
4. `ncu -p yarn --target minor`

## Current Behavior
```
Using yarn
Checking /tmp/test-a/package.json
[====================] 1/1 100%

 @progress/kendo-drawing  ^1.10.1  →  ^1.13.7
```

## Expected Behavior
```
Using yarn
Checking /tmp/test-a/package.json
[====================] 1/1 100%

All dependencies match the latest package versions :)
```
This is the behaviour without targeting only minor versions, or without using yarn.

### PR DESCRIPTION
**Pull request by midgleyc**
Fixes #906.

Re-use the npm filters in the yarn file. Don't include the peer dependencies, because I wasn't sure about that bit.

Now, `newest`, `greatest`, `minor`, `patch` differ only in the `filterPredicates` function, so this could be extracted. I left it as it was for now, though.

### CODE REVIEW

File: src/package-managers/npm.ts [hunk 1]
```diff
@@ -151,40 +152,11 @@ export async function viewOne(packageName: string, field: string, currentVersion
...
-function satisfiesPeerDependencies(versionResult: Packument, peerDependencies: Index<Index<Version>>) {
-  if (!peerDependencies) return true
-  return Object.values(peerDependencies).every(
-    peers => peers[versionResult.name] === undefined || semver.satisfies(versionResult.version, peers[versionResult.name])
-  )
-}
-
 /** Returns a composite predicate that filters out deprecated, prerelease, and node engine incompatibilies from version objects returns by pacote.packument. */
-function filterPredicate(options: Options): (o: Packument) => boolean {
+export function filterPredicate(options: Options): (o: Packument) => boolean {
```
Comment (raineorshine) [inline src/package-managers/npm.ts:156]: `export` is not needed

File: src/package-managers/yarn.ts [hunk 2]
```diff
@@ -78,33 +78,13 @@ async function parseJsonLines(result: string): Promise<{ dependencies: Index<Par
...
-  const minVersion = _.get(semver.minVersion(nodeEngineVersion), 'version')
-  if (!minVersion) return Object.keys(versions)
-
-  return versions.filter(version => {
-    const versionEnginesNode = _.get(version, 'engines.node')
-    return versionEnginesNode &&
-      semver.satisfies(minVersion, versionEnginesNode)
-  })
+/** Returns a composite predicate that filters out deprecated, prerelease, and node engine incompatibilies from version objects returns by pacote.packument. */
+export function filterPredicate(options: Options): (o: Packument) => boolean {
```
Comment (raineorshine) [inline src/package-managers/yarn.ts:82]: `export` is not needed

**Review by raineorshine — APPROVED** [review]
