### PR TITLE
fix #1325 - setting errorLevel in workspaces doesn't work as expected

### LINKED ISSUE #1325: setting errorLevel in workspaces doesn't work as expected
- [x] I have searched for [similar issues](https://github.com/raineorshine/npm-check-updates/issues)
- [x] I am using the latest version of `npm-check-updates`
- [x] I am using `node >= 14.14`

---

## Steps to Reproduce

Steps:

- Create a mono repo, with 2 workspaces that have upgrades available to them (each)
- Run in the root of the monorepo
```bash
yarn ncu --cache --workspaces --root --enginesNode --target minor --upgrade --errorLevel 2
```

## Current Behavior

The script will exit with error code, after it upgrades the first workspace, without upgrading the 2nd workspace

## Expected Behavior

If no actual error occurred, need to run all workspaces, and decide on exist status at the end - if there are upgrades needed in any of the workspace, error, otherwise, not.
This allow to conditional run commands, if *any* of the workspaces requires an update

### PR DESCRIPTION
**Pull request by regevbr**
fix #1325

### CODE REVIEW

**Comment by regevbr** [comment]
@raineorshine I would appreciate your CR

File: src/index.ts [hunk 1]
```diff
@@ -219,12 +223,15 @@ async function runUpgrades(options: Options, timeout?: NodeJS.Timeout): Promise<
...
               // convert Windows path to *nix path for consistency
               .replace(/\\/g, '/')
-          : pkgFile!]: await runLocal(pkgOptions, pkgData, pkgFile),
+          : pkgFile!]: runResult,
       }
     }, Promise.resolve({} as Index<PackageFile> | PackageFile))
     if (options.json) {
       printJson(options, analysis)
     }
+    if (totalUpgradedCount > 0 && options.errorLevel === 2) {
```
Comment (raineorshine) [inline src/index.ts:232]: I think we can just check if the `analysis` is empty. Then we don't have to alter the return type or add other variables. 

See the `someUpgraded` variable in the `npmInstall` function.

**Review by raineorshine — CHANGES_REQUESTED** [review]
Thanks for the PR!

File: src/index.ts (hunk 1 above)
Comment (regevbr) [reply src/index.ts]: Ok perfect changed it - it is a much smaller change now. I wasn't too sure about the structure of the response

File: src/index.ts [hunk 2]
```diff
@@ -209,6 +209,7 @@ async function runUpgrades(options: Options, timeout?: NodeJS.Timeout): Promise<
         ...rcConfig,
         packageFile: packageInfo.filepath,
         workspacePackages,
+        errorLevel: 1,
```
Comment (raineorshine) [inline src/index.ts:212]: Why set `errorLevel` here?

**Review by raineorshine — COMMENTED** [review]
Thanks! That looks better. Just one question for you.

File: src/index.ts (hunk 2 above)
Comment (regevbr) [reply src/index.ts:212]: if we do not, it will throw if there are upgrades, which is the current behaviour we are trying to fix

Comment (raineorshine) [reply src/index.ts:212]: Okay, thanks. It seems wrong that we have to hardcode this here when the default value of `errorLevel` is already 1. Maybe we can consolidate the workspace and non-workspace logic to avoid this? 

I will need to take a closer look at how it's handled to know. I'm not available as much right since I'm traveling, but I can check it out soon.

Comment (regevbr) [reply src/index.ts:212]: the default is indeed 1, but in my use case, we pass 2, thus causing it to exist on the first workspace that needs updating. This will ensure that it will not error on first workspace.
If you want, we can instead pass a flag to runLocal that instructs to not exit on upgrades needed. What do you think?

Comment (raineorshine) [reply src/index.ts:212]: If we need to override the  errorLevel passed to `runLocal`, then the exit logic is probably in the wrong place. Without having looked at the code yet, I'm thinking we need to return early from `runLocal` but only exit the process at the end.

Comment (regevbr) [reply src/index.ts:212]: I think I see your point - I will make the change

Comment (regevbr) [reply src/index.ts]: Done - cleaner code now

**Review by raineorshine — APPROVED** [review]
💯
