### PR TITLE
Fix Yarn `setNpmAuthToken` bug when registry URL contains trailing slash

### LINKED ISSUE #1109: Custom npm registry server not working with Yarn 2+
- [x] I have searched for [similar issues](https://github.com/raineorshine/npm-check-updates/issues)
- [x] I am using the latest version of `npm-check-updates`
- [x] I am using `node >= 12`

---------------------------

## Steps to Reproduce

1. Use Yarn 3: `yarn set version berry`
2. Configure FontAwesome custom registry in `.yarnrc.yml` like this:

    ```yaml
    npmScopes:
      fortawesome:
        npmAlwaysAuth: true
        npmAuthToken: YOUR-AUTH-TOKEN
        npmRegistryServer: "https://npm.fontawesome.com/"
    ```

3. Add a FontAwesome Pro dependency: `yarn add @fortawesome/pro-duotone-svg-icons`
4. Run `npm-check-updates`

## Current Behavior

```text
FetchError: Request @fortawesome/pro-duotone-svg-icons info failed[3 of 3]: 
Unable to authenticate, need: Basic realm="https://npm.fontawesome.com/",service="npm.fontawesome.com".
```

## Expected Behavior

npm-check-updates gets the auth token from `.yarnrc.yml` so that the requests succeed.

I may try to submit a PR for this. Let me know if you have any implementation guidance.

### PR DESCRIPTION
**Pull request by srmagura**
Closes #1109. 

- The error occurred if the `npmRegistryServer` in `.yarnrc.yml` contained a trailing slash. 
- This caused the `setNpmAuthToken` function in `yarn.ts` to add the key `//npm.fontawesome.com//:_authToken` to the `npmConfig`.
- The double slash before `:_authToken` is incorrect and resulted in the auth token not being included in the request.

### CODE REVIEW

File: src/package-managers/yarn.ts [hunk 1]
```diff
@@ -31,15 +31,32 @@ interface YarnConfig {
...
+  if (scopedConfig.npmAuthToken) {
+    // get registry server from this config or a previous config (assumes setNpmRegistry has already been called on all npm scopes)
+    const registryServer = scopedConfig.npmRegistryServer || npmConfig[`@${dep}:registry`] as string | undefined
+    // interpolate environment variable fallback
+    // https://yarnpkg.com/configuration/yarnrc
+    if (registryServer) {
+      let trimmedRegistryServer = registryServer.replace(/^https?:/, '')
+
+      if (trimmedRegistryServer.endsWith('/')) {
+        trimmedRegistryServer = trimmedRegistryServer.substring(0, trimmedRegistryServer.length - 1)
```
Comment (raineorshine) [inline src/package-managers/yarn.ts:48]: Prefer `trimmedRegistryServer.slice(0, -1)`

File: src/package-managers/yarn.ts [hunk 2]
```diff
@@ -31,15 +31,32 @@ interface YarnConfig {
...
+
+/** Reads an auth token from a yarn config, interpolates it, and sets it on the npm config. */
+export const setNpmAuthToken = (npmConfig: Index<string|boolean>, [dep, scopedConfig]: [string, NpmScope]) => {
+  if (scopedConfig.npmAuthToken) {
+    // get registry server from this config or a previous config (assumes setNpmRegistry has already been called on all npm scopes)
+    const registryServer = scopedConfig.npmRegistryServer || npmConfig[`@${dep}:registry`] as string | undefined
+    // interpolate environment variable fallback
+    // https://yarnpkg.com/configuration/yarnrc
+    if (registryServer) {
+      let trimmedRegistryServer = registryServer.replace(/^https?:/, '')
```
Comment (raineorshine) [inline src/package-managers/yarn.ts:45]: Prefer `const`

**Review by raineorshine — APPROVED** [review]
Looks good, thanks!

**Comment by raineorshine** [comment]
Published in `v12.5.12`

File: src/package-managers/yarn.ts (hunk 1 above)
Comment (srmagura) [reply src/package-managers/yarn.ts:48]: Nice, did not know that one!

File: src/package-managers/yarn.ts (hunk 2 above)
Comment (srmagura) [reply src/package-managers/yarn.ts:45]: The variable gets reassigned a few lines after this, hence the `let` 😉

Comment (raineorshine) [reply src/package-managers/yarn.ts:45]: I try to avoid `let` when there are ways to do the same thing without mutations:

```
const trimmedRegistryServer = registryServer
  .replace(/^https?:/, '')
  .replace(/\/$/, '')
```
